build_run: build run

build:
	g++ -g main.cpp language/cursor.cpp language/match.cpp language/languagelexer.cpp gdxlanguage/gdxlanguagelexer.cpp gdxlanguage/gdxlanguageparser.cpp -o main

run:
	./main

