build_run: build run

build:
	g++ main.cpp ../language/cursor.cpp ../language/match.cpp ../language/languagelexer.cpp ../gdxlanguage/gdxlanguagelexer.cpp ../gdxlanguage/gdxlanguageparser.cpp -o main.exe

run:
	./main.exe

